### ISSUE TITLE
[FE] 리액트 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by yeahzee0421** [MangoSiruu/nonToxicDiary#1]
### 🤔 Describe
Vite+React 프로젝트 세팅
Eslint, Prettier 세팅 
추가 라이브러리 설치

### ✅ Tasks
- [x] Vite+React 프로젝트 세팅
- [x] Eslint 세팅 (Airbnb)
- [x] Prettier 세팅
- [x] reset.css 작성
- [x] variants 작성

### 라이브러리
- @emotion/styled
- chakra-ui
- zustand
- react-router-dom
- react-query
- react-error-boundary
- react-intersection-observer
- react-hook-form
- react-icons
