### ISSUE TITLE
[FE] jwt 토큰을 사용한 인증 서비스 및 로그아웃 구현

### ISSUE THREAD

**Issue by yeahzee0421** [MangoSiruu/nonToxicDiary#4]
### 📄 Describe
유저 인증 서비스를 구현합니다.
회원가입 성공 시 `localStorage`에 유저의 닉네임, id을 저장합니다.
`authStore`에서는 유저정보를 담은 `authInfo`와 인증여부를 담는 `isAuthenticated`상태를 관리합니다.

### ✅ Tasks
- [x] 인증 서비스 구현
- [x] 로그아웃 구현(localStorage의 `clear` 메서드 사용)
- [x] refreshToken logic
- [x] AuthProvider 대신 zustand로 인증 정보 전역 관리하도록 리팩터링

### 🙋🏻 More
최대한 간단하게 구현하려고 합니다.
