### ISSUE TITLE
[FE] Calendar 기타 기능 

### ISSUE THREAD

**Issue by leumi802** [MangoSiruu/nonToxicDiary#45]
### 📄 Describe
이것 저것 여러가지 기능 

### ✅ Tasks
해야 하는 일에 대한 Tasks를 작성해 주세요.
- [x] 캘린더에 오늘 날짜 하이라이트
- [x] 캘린더 페이지 월별리포트 제작
- [x] 캘린더 페이지 연결 및 컴포넌트 배치
